name: main
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
      - run: npm ci
      - name: Execute test
        run: npm run ci
      - name: Public coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: publish
    runs-on: ubuntu-22.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/') 
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
      - run: npm ci
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}